### PR TITLE
complete implementation of 'connect'

### PR DESCRIPTION
**Pull request by boegel**
`'hod connect <label>` now works as intended after `hod create --label <label>` was used

if no label was specfied, the job ID is used as a fallback label

TODO:

* make `create` check whether label is not in use already
* mention label in output of `hod list` (and fix https://github.com/hpcugent/hanythingondemand/issues/62 along the way)
* implement `hod cleanup` to cleanup cluster-info directory (so labels can be recovered)
   * probably out of scope for https://github.com/hpcugent/hanythingondemand/pull/49

### CODE REVIEW

**Comment by boegel** [comment]
Example output (no label specified, so job ID becomes the label to use in `connect`):

```
$ hod create --dist=IPython-notebook-3.2.1
Submitting HOD cluster with label 'None'...
Jobs submitted: ['Jobid  100574.master20.golett.gent.vsc state Q ehosts ']

$ hod connect 100574.master20.golett.gent.vsc
Connecting to HOD cluster with label '100574.master20.golett.gent.vsc'...
Job ID found: 100574.master20.golett.gent.vsc
2015-08-28 16:55:27,417 ERROR      runpy.Pbs       MainThread  Request for jobid None returned more then one result [<pbs.batch_status; proxy of <Swig Object of type 'batch_status *' at 0x2b60f8bd1cc0> >, <pbs.batch_status; proxy of <Swig Object of type 'batch_status *' at 0x2b60f8bd1cf0> >, <pbs.batch_status; proxy of <Swig Object of type 'batch_status *' at 0x2b60f8bd1d20> >]
HOD cluster '100574.master20.golett.gent.vsc' @ job ID 100574.master20.golett.gent.vsc appears to be running...
Setting up SSH connection to node2589.golett.gent.vsc...
Warning: Permanently added 'node2589.golett.gent.vsc,172.24.18.190' (RSA) to the list of known hosts.
Welcome to your hanythingondemand cluster (label: 100574.master20.golett.gent.vsc)

Relevant environment variables:
HADOOP_CONF_DIR=/user/scratch/gent/vsc400/vsc40023/hod/hod/vsc40023.node2589.golett.os.15604/conf
HADOOP_HOME=/apps/gent/CO7/haswell-ib/software/Hadoop/2.6.0-cdh5.4.5-native/share/hadoop/mapreduce
HOD_LOCALWORKDIR=/user/scratch/gent/vsc400/vsc40023/hod/hod/vsc40023.node2589.golett.os.15604

List of loaded modules:
Currently Loaded Modulefiles:
  1) cluster/golett(default)                        7) ifort/2015.1.133-GCC-4.9.2                    13) bzip2/1.0.6-intel-2015a                       19) Tk/8.6.4-intel-2015a-no-X11                   25) PyZMQ/14.7.0-intel-2015a-Python-2.7.10-zmq4
  2) Java/1.7.0_80                                  8) iccifort/2015.1.133-GCC-4.9.2                 14) zlib/1.2.8-intel-2015a                        20) Python/2.7.10-intel-2015a                     26) IPython/3.2.1-intel-2015a-Python-2.7.10
  3) Hadoop/2.6.0-cdh5.4.5-native                   9) impi/5.0.2.044-iccifort-2015.1.133-GCC-4.9.2  15) ncurses/5.9-intel-2015a                       21) OpenPGM/5.2.122-intel-2015a                   27) libpng/1.6.16-intel-2015a
  4) Spark/1.4.1                                   10) iimpi/7.2.3-GCC-4.9.2                         16) libreadline/6.3-intel-2015a                   22) util-linux/2.26.2-intel-2015a                 28) freetype/2.5.5-intel-2015a
  5) GCC/4.9.2                                     11) imkl/11.2.1.133-iimpi-7.2.3-GCC-4.9.2         17) Tcl/8.6.4-intel-2015a                         23) libsodium/1.0.3-intel-2015a                   29) matplotlib/1.4.3-intel-2015a-Python-2.7.10
  6) icc/2015.1.133-GCC-4.9.2                      12) intel/2015a                                   18) SQLite/3.8.10.2-intel-2015a                   24) ZeroMQ/4.1.3-intel-2015a
```

**Comment by ehiggs** [comment]
This doesn't pass tests.

**Comment by ehiggs** [comment]
:shipit:

**Comment by ehiggs** [comment]
TODOs were pushed out to #64 and #65.

**Pull request merged**
